
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: sakthiaps2695
  host: localhost
  pool: 5
  timeout: 5000
  port: 5432


development:
  <<: *default
  database: car_parking_development

test:
  <<: *default
  database: car_parking_test


